#pragma config(Sensor, in1,    potentiometer,  sensorPotentiometer)
#pragma config(Sensor, dgtl5,  chainBarEncoder, sensorQuadEncoder)
#pragma config(Sensor, dgtl1,  encoderLeft,    sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  encoderRight,   sensorQuadEncoder)
#pragma config(Motor,  port2,           leftDirect,    tmotorVex393HighSpeed_MC29, openLoop, encoderPort, dgtl1)
#pragma config(Motor,  port3,           leftNonDirect, tmotorVex393HighSpeed_MC29, openLoop, reversed, encoderPort, dgtl1)
#pragma config(Motor,  port4,           rightDirect,   tmotorVex393HighSpeed_MC29, openLoop, reversed, encoderPort, dgtl3)
#pragma config(Motor,  port5,           rightNonDirect, tmotorVex393HighSpeed_MC29, openLoop, encoderPort, dgtl3)
#pragma config(Motor,  port6,           mobileGoal,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           fourBar,       tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port8,           chainBar,      tmotorVex393HighSpeed_MC29, openLoop, reversed, encoderPort, dgtl5)
#pragma config(Motor,  port9,           claw,          tmotorVex393HighSpeed_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void stackCone1(){
	if (SensorValue[chainBarEncoder] > 23)
		motor[chainBar] = 127;
	else if (SensorValue[chainBarEncoder] < 18)
		motor[chainBar] = -127;
	else
		motor[chainBar] = 0;
}

void stackCone2(){
	if (SensorValue[chainBarEncoder] > 40)
		motor[chainBar] = 127;
	else if (SensorValue[chainBarEncoder] < 35)
		motor[chainBar] = -127;
	else
		motor[chainBar] = 0;
}

void stackCone3(){
	if (SensorValue[chainBarEncoder] > 55)
		motor[chainBar] = 127;
	else if (SensorValue[chainBarEncoder] < 50)
		motor[chainBar] = -127;
	else
		motor[chainBar] = 0;
}

void stackCone4(){
	while (SensorValue[potentiometer] > 2350)
		motor[fourBar] = 127;
	while (SensorValue[chainBarEncoder] > 30)
		motor[chainBar] = 127;
	if (SensorValue[chainBarEncoder] < 20)
		motor[chainBar] = -127;
}

void stackCone6(){
	while (SensorValue[potentiometer] > 2350)
		motor[fourBar] = 127;
	while (SensorValue[chainBarEncoder] > 40)
		motor[chainBar] = 127;
	if (SensorValue[chainBarEncoder] < 30)
		motor[chainBar] = -127;
}

void stackCone7(){
	while (SensorValue[potentiometer] > 2600)
		motor[fourBar] = 127;
	motor[fourBar] = 10;
	while (SensorValue[chainBarEncoder] > 50)
		motor[chainBar] = 127;
	if (SensorValue[chainBarEncoder] < 40)
		motor[chainBar] = -127;
}

void stackCone8(){
	while (SensorValue[potentiometer] > 2350)
		motor[fourBar] = 127;
	while (SensorValue[chainBarEncoder] > 75)
		motor[chainBar] = 127;
	if (SensorValue[chainBarEncoder] < 65)
		motor[chainBar] = -127;
}
task main{
	float Kp = .5, Ki = .5, Kd = .5;
	int fourBarRequested = 0, chainBarRequested = 0;
	int fourBarErrorNow = 0, chainBarErrorNow = 0;
	int fourBarErrorPrevious = 0, chainBarErrorPrevious = 0;
	int fourBarErrorOverall = 0, chainBarErrorOverall = 0;
	motor[fourBar] = 0;
	wait1Msec(50);
	SensorValue[potentiometer] = 0;
	motor[claw] = 0;
	while (true){
		//-----------------------------------------------------------------------------------------
		if(abs(vexRT[Ch3]) > 20 || abs(vexRT[Ch4])>20){ // arcade DT code
			motor[leftDirect] = motor[leftNonDirect] = vexRT[Ch3] + vexRT[Ch4];
			motor[rightDirect] = motor[rightNonDirect] = vexRT[Ch3] - vexRT[Ch4];}
		else
			motor[leftDirect] = motor[leftNonDirect] = motor[rightDirect] = motor[rightNonDirect] = 0;
		//------------------------------------------------------------------------------------------
		if(vexRT[Btn6D] == 1) //Code to control Mobile Goal Manipulator. Right side Rear buttons.
			motor[mobileGoal] = 127;
		if(vexRT[Btn6U] == 1)
			motor[mobileGoal] = -127;
		if(vexRT[Btn6U]==0 && vexRT[Btn6D] == 0 )
			motor[mobileGoal] = 0;
		//--------------------------------------------------------------------------------------------
		if (vexRT[Btn5U] == 1){
			motor[fourBar] = 127;
			fourBarRequested = SensorValue[potentiometer];
		}
		else if (vexRT[Btn5D] == 1){
			motor[fourBar] = -127;
			fourBarRequested = SensorValue[potentiometer];
		}
		else if (vexRT[Btn5U] == 0 && vexRT[Btn5D] == 0){
			fourBarErrorPrevious = fourBarErrorNow;
			fourBarErrorNow = fourBarRequested - SensorValue[potentiometer];
			fourBarErrorOverall = (Kp)*(fourBarErrorNow) + (Kd)*((fourBarErrorNow - fourBarErrorPrevious)/.02);
			if (fourBarErrorOverall > 0){
				motor[fourBar] = -10;
			}
			if (fourBarErrorOverall < 0){
				motor[fourBar] = 10;
			}
		}
		else{
			motor[fourBar] = 0;
		}
		//------------------------------------------------------------------------------------------------
		if (abs(vexRT[Ch2]) > 20 && SensorValue[chainBarEncoder] < 280 && SensorValue[chainBarEncoder] > -10){
			motor[chainBar] = vexRT[Ch2];
			chainBarRequested = SensorValue[chainBarEncoder];
		}
		else if(abs(vexRT[Ch2])<20){
			chainBarErrorPrevious = chainBarErrorNow;
			chainBarErrorNow = chainBarRequested - SensorValue[chainBarEncoder];
			chainBarErrorOverall = (Kp)*(chainBarErrorNow) + (Kd)*((chainBarErrorNow - chainBarErrorPrevious)/.02);
			if (chainBarErrorOverall < 0)
				motor[chainBar] = 9;
			if (chainBarErrorOverall > 0)
				motor[chainBar] = -9;
		}
		if (SensorValue[chainBarEncoder] > 280 && vexRT[Ch2] > 20)
			motor[chainBar] = vexRT[Ch2];
		if (SensorValue[chainBarEncoder] < -10 && vexRT[Ch2] < -20)
			motor[chainBar] = vexRT[Ch2];
		//-----------------------------------------------------------------------------------------------
		if (vexRT[Btn7LXmtr2] == 1){//pre set stacks
			stackCone1();
			chainBarRequested = SensorValue[chainBarEncoder];
		}
		if (vexRT[Btn7UXmtr2] == 1){
			stackCone2();
			chainBarRequested = SensorValue[chainBarEncoder];
		}
		if (vexRT[Btn7RXmtr2] == 1){
			stackCone3();
			chainBarRequested = SensorValue[chainBarEncoder];
		}
		if (vexRT[Btn7DXmtr2] == 1){
			stackCone4();
			//stackCone4_2();
			chainBarRequested = SensorValue[chainBarEncoder];
			fourBarRequested = SensorValue[potentiometer];
		}
		if (vexRT[Btn8LXmtr2] == 1){
			stackCone4();
			fourBarRequested = SensorValue[chainBarEncoder];
			chainBarRequested = SensorValue[potentiometer];
		}
		if (vexRT[Btn8UXmtr2]){
			stackCone6();
			fourBarRequested = SensorValue[chainBarEncoder];
			chainBarRequested = SensorValue[potentiometer];
		}
		if (vexRT[Btn8RXmtr2]){
			stackCone7();
			fourBarRequested = SensorValue[chainBarEncoder];
			chainBarRequested = SensorValue[potentiometer];
		}
		if (vexRT[Btn8DXmtr2]){
			stackCone8();
			fourBarRequested = SensorValue[chainBarEncoder];
			chainBarRequested = SensorValue[potentiometer];
		}
		//-------------------------------------------------------------------------------------------------
		if(vexRT[Btn6UXmtr2] == 1) // code for roller intake
			motor[claw] = 127;
		if(vexRT[Btn6DXmtr2] == 1)
			motor[claw] = -127;
		if (vexRT[Btn6DXmtr2] == 0 && vexRT[Btn6UXmtr2] ==0)
			motor[claw] = 0;
	}
}
